name: 'Integration tests'
description: 'Execute integration tests'

inputs:
  XOAUTH2_RELAYHOST_USERNAME:
    description: 'Username'
    required: true
  XOAUTH2_CLIENT_ID:
    description: 'OAuth CLIENT_ID'
    required: true
  XOAUTH2_SECRET:
    description: 'OAuth secret'
    required: true
  XOAUTH2_INITIAL_REFRESH_TOKEN:
    description: 'Refresh token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run integration tests
      shell: bash
      env: # Or as an environment variable
        XOAUTH2_RELAYHOST_USERNAME: ${{ inputs.XOAUTH2_RELAYHOST_USERNAME }}
        XOAUTH2_CLIENT_ID: ${{ inputs.XOAUTH2_CLIENT_ID }}
        XOAUTH2_SECRET: ${{ inputs.XOAUTH2_SECRET }}
        XOAUTH2_INITIAL_REFRESH_TOKEN: ${{ inputs.XOAUTH2_INITIAL_REFRESH_TOKEN }}
      run: |
        echo "RELAYHOST_USERNAME=${XOAUTH2_RELAYHOST_USERNAME}" > integration-tests/xoauth2/.env
        echo "FROM=${XOAUTH2_RELAYHOST_USERNAME}" >> integration-tests/xoauth2/.env
        echo "TO=${XOAUTH2_RELAYHOST_USERNAME}" >> integration-tests/xoauth2/.env
        echo "XOAUTH2_CLIENT_ID=${XOAUTH2_CLIENT_ID}" >> integration-tests/xoauth2/.env
        echo "XOAUTH2_SECRET=${XOAUTH2_SECRET}" >> integration-tests/xoauth2/.env
        echo "XOAUTH2_INITIAL_REFRESH_TOKEN=${XOAUTH2_INITIAL_REFRESH_TOKEN}" >> integration-tests/xoauth2/.env
        cp integration-tests/xoauth2/.env integration-tests/xoauth2-error/.env
        ./integration-tests.sh
